trigger:
  branches:
    include:
      - main

pool:
  name: SmartCampusLocal

variables:
  buildConfiguration: Release
  project: SmartCampusHelpDesk/SmartCampusHelpDesk.csproj
  testProject: SmartCampusHelpDesk.Tests/SmartCampusHelpDesk.Tests.csproj

stages:
- stage: CI
  displayName: Restore Build Test Publish
  jobs:
  - job: Build
    displayName: CI
    steps:
    - task: UseDotNet@2
      displayName: Use .NET 8
      inputs:
        packageType: sdk
        version: 8.x

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(project)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(testProject)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(project)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/app --no-restore'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: drop
        publishLocation: Container
